import { EmployeeWithDetails } from '@/types'

export const INITIAL_MOCK_EMPLOYEES: EmployeeWithDetails[] = [
  {
    id: 'emp-1',
    organization_id: 'org-1',
    profile_id: 'prof-1',
    full_name: 'Lucas Silveira Mendes',
    email: 'lucas.mendes@limarh.com',
    phone: '(11) 98765-4321',
    birth_date: '1995-04-12',
    contract_type: 'CLT',
    job_title: 'Desenvolvedor Full Stack Pleno',
    department: 'Engenharia de Software',
    manager_id: 'mgr-1',
    admission_date: '2025-02-01',
    resignation_date: null,
    status: 'ativo',
    salary_or_rate: 8500,
    created_at: new Date(Date.now() - 180 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    manager: {
      id: 'mgr-1',
      full_name: 'Carlos Eduardo Ramos (CTO)',
    },
    clt_details: {
      id: 'clt-1',
      employee_id: 'emp-1',
      cpf: '345.678.901-23',
      rg: '45.678.901-2',
      pis_pasep: '123.45678.90-1',
      ctps_number: '7891234',
      ctps_series: '0010',
      transport_voucher: false,
      meal_voucher_value: 900,
      health_insurance: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: 'emp-2',
    organization_id: 'org-1',
    profile_id: 'prof-2',
    full_name: 'Mariana Duarte Costa',
    email: 'mariana.costa@limarh.com',
    phone: '(21) 99123-8877',
    birth_date: '1992-08-25',
    contract_type: 'PJ',
    job_title: 'Product Designer Sênior',
    department: 'Design & UX',
    manager_id: 'mgr-2',
    admission_date: '2024-11-15',
    resignation_date: null,
    status: 'ativo',
    salary_or_rate: 13500,
    created_at: new Date(Date.now() - 250 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    manager: {
      id: 'mgr-2',
      full_name: 'Ana Paula Rocha (Head de Produto)',
    },
    pj_details: {
      id: 'pj-1',
      employee_id: 'emp-2',
      company_name: 'M. Duarte Design & Inovação LTDA',
      trade_name: 'Duarte UX Studio',
      cnpj: '38.912.456/0001-89',
      invoice_due_day: 10,
      contract_valid_until: '2026-11-15',
      contract_file_url: 'https://storage.supabase.co/limarh/contracts/emp-2-contract.pdf',
      bank_name: 'Banco Itaú',
      bank_agency: '0345',
      bank_account: '12984-5',
      pix_key: '38912456000189',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: 'emp-3',
    organization_id: 'org-1',
    profile_id: 'prof-3',
    full_name: 'Rodrigo Barbosa Alencar',
    email: 'rodrigo.alencar@limarh.com',
    phone: '(31) 98455-1234',
    birth_date: '1989-11-03',
    contract_type: 'CLT',
    job_title: 'Especialista em Banco de Dados',
    department: 'Engenharia de Software',
    manager_id: 'mgr-1',
    admission_date: '2023-06-10',
    resignation_date: null,
    status: 'ferias',
    salary_or_rate: 14000,
    created_at: new Date(Date.now() - 600 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    manager: {
      id: 'mgr-1',
      full_name: 'Carlos Eduardo Ramos (CTO)',
    },
    clt_details: {
      id: 'clt-2',
      employee_id: 'emp-3',
      cpf: '567.890.123-45',
      rg: '23.456.789-0',
      pis_pasep: '987.65432.10-9',
      ctps_number: '1234567',
      ctps_series: '0020',
      transport_voucher: false,
      meal_voucher_value: 1200,
      health_insurance: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: 'emp-4',
    organization_id: 'org-1',
    profile_id: 'prof-4',
    full_name: 'Camila Ferreira Lima',
    email: 'camila.lima@limarh.com',
    phone: '(41) 99888-7766',
    birth_date: '1998-02-17',
    contract_type: 'PJ',
    job_title: 'Consultora de People Analytics',
    department: 'Gente & Gestão',
    manager_id: 'mgr-2',
    admission_date: '2025-01-10',
    resignation_date: null,
    status: 'ativo',
    salary_or_rate: 9000,
    created_at: new Date(Date.now() - 100 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    manager: {
      id: 'mgr-2',
      full_name: 'Ana Paula Rocha (Head de Gente)',
    },
    pj_details: {
      id: 'pj-2',
      employee_id: 'emp-4',
      company_name: 'CFL Consultoria em RH e Dados LTDA',
      trade_name: 'Lima People Insights',
      cnpj: '45.123.789/0001-12',
      invoice_due_day: 5,
      contract_valid_until: '2026-01-10',
      contract_file_url: 'https://storage.supabase.co/limarh/contracts/emp-4-contract.pdf',
      bank_name: 'Nubank (Nu Pagamentos)',
      bank_agency: '0001',
      bank_account: '9876543-2',
      pix_key: 'camila.lima@peopleinsights.com.br',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
]
